// <auto-generated />
using System;
using Dao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dao.Migrations
{
    [DbContext(typeof(ApiF1DB))]
    partial class ApiF1DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.CarData", b =>
                {
                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Brake")
                        .HasColumnType("int");

                    b.Property<int?>("Drs")
                        .HasColumnType("int");

                    b.Property<int>("Gear")
                        .HasColumnType("int");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("Rpm")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Throttle")
                        .HasColumnType("int");

                    b.HasKey("SessionKey", "DriverNumber", "Date");

                    b.ToTable("F1_CARDATAS", (string)null);
                });

            modelBuilder.Entity("Entities.Class.LapSegment", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<int>("LapNumber")
                        .HasColumnType("int");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("int");

                    b.Property<int?>("SegmentStatus")
                        .HasColumnType("int");

                    b.HasKey("MeetingKey", "SessionKey", "DriverNumber", "LapNumber", "Sector", "SegmentIndex");

                    b.ToTable("F1_LAPS_SEGMENTS", (string)null);
                });

            modelBuilder.Entity("Entities.Class.SessionResultQualify", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<string>("QualifyingPhase")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<double>("GapToLeader")
                        .HasColumnType("float");

                    b.HasKey("MeetingKey", "SessionKey", "DriverNumber", "QualifyingPhase");

                    b.ToTable("F1_SESSION_RESULTS_QUALIFYINGS", (string)null);
                });

            modelBuilder.Entity("Entities.Driver", b =>
                {
                    b.Property<int>("DriverKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverKey"));

                    b.Property<string>("BroadcastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HeadshotUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<string>("NameAcronym")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<string>("TeamColour")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DriverKey");

                    b.HasIndex("DriverKey");

                    b.HasIndex("MeetingKey");

                    b.HasIndex("SessionKey");

                    b.ToTable("F1_DRIVERS", (string)null);
                });

            modelBuilder.Entity("Entities.Lap", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<int>("LapNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<double>("DurationSector1")
                        .HasColumnType("float");

                    b.Property<double>("DurationSector2")
                        .HasColumnType("float");

                    b.Property<double>("DurationSector3")
                        .HasColumnType("float");

                    b.Property<int>("I1Speed")
                        .HasColumnType("int");

                    b.Property<int>("I2Speed")
                        .HasColumnType("int");

                    b.Property<bool>("IsPitOutLap")
                        .HasColumnType("bit");

                    b.Property<double>("LapDuration")
                        .HasColumnType("float");

                    b.Property<int>("StSpeed")
                        .HasColumnType("int");

                    b.HasKey("MeetingKey", "SessionKey", "DriverNumber", "LapNumber");

                    b.ToTable("F1_LAPS", (string)null);
                });

            modelBuilder.Entity("Entities.Meeting", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<string>("CircuitImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CircuitInfoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CircuitKey")
                        .HasColumnType("int");

                    b.Property<string>("CircuitShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CircuitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CountryKey")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DateEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GmtOffset")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MeetingName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MeetingOfficialName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MeetingKey");

                    b.HasIndex("CircuitKey");

                    b.HasIndex("Year");

                    b.ToTable("F1_MEETINGS", (string)null);
                });

            modelBuilder.Entity("Entities.Overtake", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("OvertakingDriverNumber")
                        .HasColumnType("int");

                    b.Property<int>("OvertakedDriverNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("MeetingKey", "SessionKey", "OvertakingDriverNumber", "OvertakedDriverNumber", "Date", "Position");

                    b.ToTable("F1_OVERTAKES", (string)null);
                });

            modelBuilder.Entity("Entities.Pit", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<double>("LaneDuration")
                        .HasColumnType("float");

                    b.Property<int>("LapNumber")
                        .HasColumnType("int");

                    b.Property<double>("PitDuration")
                        .HasColumnType("float");

                    b.Property<double?>("StopDuration")
                        .HasColumnType("float");

                    b.HasKey("Date", "DriverNumber", "SessionKey", "MeetingKey");

                    b.ToTable("F1_PITS", (string)null);
                });

            modelBuilder.Entity("Entities.RaceControl", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<string>("Flag")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("LapNumber")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("QualifyingPhase")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Sector")
                        .HasColumnType("int");

                    b.HasKey("Date", "SessionKey", "MeetingKey");

                    b.ToTable("F1_RACE_CONTROLS", (string)null);
                });

            modelBuilder.Entity("Entities.Session", b =>
                {
                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("CircuitKey")
                        .HasColumnType("int");

                    b.Property<string>("CircuitShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CountryKey")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DateEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GmtOffset")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SessionKey");

                    b.HasIndex("CircuitKey");

                    b.HasIndex("MeetingKey");

                    b.HasIndex("Year");

                    b.ToTable("F1_SESSION", (string)null);
                });

            modelBuilder.Entity("Entities.SessionResult", b =>
                {
                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<string>("Compound")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Dnf")
                        .HasColumnType("bit");

                    b.Property<bool>("Dns")
                        .HasColumnType("bit");

                    b.Property<bool>("Dsq")
                        .HasColumnType("bit");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("GapToLeader")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsQualy")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLaps")
                        .HasColumnType("int");

                    b.Property<double>("Points")
                        .HasColumnType("float");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("SessionKey", "DriverNumber");

                    b.ToTable("F1_SESSION_RESULTS", (string)null);
                });

            modelBuilder.Entity("Entities.Stint", b =>
                {
                    b.Property<int>("MeetingKey")
                        .HasColumnType("int");

                    b.Property<int>("SessionKey")
                        .HasColumnType("int");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("int");

                    b.Property<int>("StintNumber")
                        .HasColumnType("int");

                    b.Property<string>("Compound")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LapEnd")
                        .HasColumnType("int");

                    b.Property<int?>("LapStart")
                        .HasColumnType("int");

                    b.Property<int>("TyreAgeAtStart")
                        .HasColumnType("int");

                    b.HasKey("MeetingKey", "SessionKey", "DriverNumber", "StintNumber");

                    b.ToTable("F1_STINTS", (string)null);
                });

            modelBuilder.Entity("Entities.Class.LapSegment", b =>
                {
                    b.HasOne("Entities.Lap", "Lap")
                        .WithMany("Segments")
                        .HasForeignKey("MeetingKey", "SessionKey", "DriverNumber", "LapNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lap");
                });

            modelBuilder.Entity("Entities.Lap", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
